### ISSUE TITLE
Problem 1.20

### ISSUE THREAD

**Issue by bethandtownes** [GoldenCheese/PRML-Solution-Manual#1]
my solution to 1.20 is also the same as yours. I believe the author made a mistake in expanding the taylor series. Plus I think he should use o() notation instead of O() for the taylor

**Comment by zhengqigao** [comment]
Yeah, I think that there is a mistake when the author expands the Taylor series. About the notation, you can see [wiki](https://en.wikipedia.org/wiki/Taylor_series), and it seems that `O()` is the right one.
