### ISSUE TITLE
Problem1.2

### ISSUE THREAD

**Issue by yooceii** [GoldenCheese/PRML-Solution-Manual#2]
The final equation seems not correct. The j=i will happen N times, so the equation will became ![](http://latex.codecogs.com/gif.latex?%5Csum_%7Bn%3D1%7D%5EN%5Csum_%7Bj%3D0%7D%5EMw_jx_n%5E%7Bi&plus;j%7D&plus;N%5Clambda%20w_i%3D%5Csum_%7Bn%3D1%7D%5ENx_n%5Eit_n)

**Comment by zhengqigao** [comment]
Hey, in the last equation, the summation with respect to `n` only acts on `x_n^{(j+i)}`. Does this make sense?

**Comment by yooceii** [comment]
Forgot the last term is not included in summation. You are right.
