### ISSUE TITLE
Minor error in Problem 10.25 Solution

### ISSUE THREAD

**Issue by dhanajitb** [GoldenCheese/PRML-Solution-Manual#4]
In page 227, I think it should be
<img src="https://user-images.githubusercontent.com/19517627/56942600-3bacd080-6b39-11e9-8dc6-53b5275b7c2e.png" width="400">

Similar correction in the expression for ln q*(w).

**Comment by zhengqigao** [comment]
Hey, thanks for your suggestion. I believe that you mean Problem 10.26, and you are right. I have revised the solution manual and update it online.
