### ISSUE TITLE
Normalization constant in Problem 11.06

### ISSUE THREAD

**Issue by DarioHett** [GoldenCheese/PRML-Solution-Manual#6]
Hey,

I was kinda confused reading your solution, so I referenced Bishops solutions,
turns out it was the normalization constant which threw me off:

Bishop uses 
![image](https://user-images.githubusercontent.com/40806448/60177494-52aa2f00-9819-11e9-82c0-93eb666f7a14.png)
![image](https://user-images.githubusercontent.com/40806448/60177522-60f84b00-9819-11e9-9aad-7f2b3de35290.png)

Where you put the Z_p into the denominator, which is in the numerator of
the fraction for Bishop's typical notation
![image](https://user-images.githubusercontent.com/40806448/60177884-512d3680-981a-11e9-8492-eeb6cb3fd59a.png)

In Bishops Solution, it then follows

![image](https://user-images.githubusercontent.com/40806448/60177624-a157c900-9819-11e9-8aba-9d0c2746ea42.png)
![image](https://user-images.githubusercontent.com/40806448/60177640-ad438b00-9819-11e9-96f2-c7fdba76919f.png)

I just wanted to leave this here for future reference.
Awesome collection of solutions by the way, thanks a lot!

**Comment by zhengqigao** [comment]
Hey, sorry for the delay of reply and thank you for the comments. You are totally right, and it is my mistake. I have already updated the solution for problem 11.6.
