### ISSUE TITLE
A typo in problem 1.26

### ISSUE THREAD

**Issue by WineChord** [GoldenCheese/PRML-Solution-Manual#7]
![image](https://user-images.githubusercontent.com/20353612/61674778-fc50e300-ad27-11e9-9c40-e06ee0f5b86c.png)
I think the equation at the bottom should be:
![image](https://user-images.githubusercontent.com/20353612/61676511-dd098400-ad2e-11e9-81d3-908817049899.png)
Alternatively, it also can be derived as:
![image](https://user-images.githubusercontent.com/20353612/61676939-4c33a800-ad30-11e9-8c8d-c1c8ccfcbff4.png)
which coincide with the [errata](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/05/prml-errata-1st-20110921.pdf):
![image](https://user-images.githubusercontent.com/20353612/61677035-9d439c00-ad30-11e9-85b8-b81c50eec630.png)

**Comment by zhengqigao** [comment]
Hey, sorry for the delay of reply and thank you for your comment. You are totally right. I didn't know that there is an errata existing :-) 

At that time I tried solve this problem, I found that Eq(1.90) was not the same as the one shown in Page 148, and I guessed that there should be a typo.

Thanks again and I have updated the manual by adding the errata link in this problem.
