### ISSUE TITLE
error problem 3.13

### ISSUE THREAD

**Issue by sillybun** [GoldenCheese/PRML-Solution-Manual#8]
The last line of p(t|X, T) is inconsistent with (2.160), for the parameter in Gamma distribution of (2.160) should be exactly the same.
Therefore the right solution for lambda should be an/bn/(1+phi'*Sn*phi)

**Comment by zhengqigao** [comment]
Hi, sorry for the delay of reply and thank you for the comments. You are right. I have missed several steps, i.e., (2.158)-(2.160).

Thanks for pointing that out. I have updated the solution manual.
