### ISSUE TITLE
Problem 2.58

### ISSUE THREAD

**Issue by owencorrigan** [GoldenCheese/PRML-Solution-Manual#9]
I think the mistake in 2.58 is caused by the line under
"If we multiply both sides by -1/g(n), we can obtain"

The left hand side should expand to 
−∇∇ln g(η)−E[u(x)]E[u(x)T]

instead of 
−∇∇ln g(η)
I've demonstrated this [here](http://mathb.in/36853)

Which causes the final solution to match the answer given in the book

Thanks for doing this by the way! Such a great resource

**Comment by zhengqigao** [comment]
Hi, sorry for the delayed reply. You are right. I have updated the solution manual.

Thanks!
